apiVersion: v1
data:
  RAILS_ENV: production
  RAKE_ENV: production
  RAILS_LOG_TO_STDOUT: "true"
  APP_ENV_TYPE: WEBSERVER
  APP_WORKER_CLASS: NONE
  APP_ENV: PRODUCTION
  APP_NAME: ReactRails
  APP_ROOT: gitlab_link
  CLOUD_PROVIDER: GCP
  DS_ENTITY: ReactRails
  GOOGLE_PROJECT_ID: react-rails
  LANG: en_US.UTF-8
  TZ: Asia/Kolkata
kind: ConfigMap
metadata:
  name: react-rails-app-config
  namespace: react-rails-production
